### PR TITLE
Fix alignment of rho constants for MSVC

### LINKED ISSUE #16: build errors under MSVC
I'm revendoring this repo into https://github.com/oconnor663/kangarootwelve_xkcp.rs, and that's triggered a build failure on Windows under MSVC. See this CI run: https://github.com/oconnor663/kangarootwelve_xkcp.rs/actions/runs/3292387615/jobs/5427689462. The error is:

```
  running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "XKCP-K12/lib" "-I" "XKCP-K12/lib/Optimized64" "-W4" "/arch:AVX2" "-DLITTLE_ENDIAN=1" "-DKeccakP1600_noAssembly=1" "-FoD:\\a\\kangarootwelve_xkcp.rs\\kangarootwelve_xkcp.rs\\target\\debug\\build\\kangarootwelve_xkcp-6c3db5c94a44740e\\out\\XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.o" "-c" "XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.c"
  KeccakP-1600-timesN-AVX2.c
  XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.c(36): error C2054: expected '(' to follow 'rho8'
  XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.c(36): error C2143: syntax error: missing ';' before '='
  XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.c(37): error C2054: expected '(' to follow 'rho56'
  XKCP-K12/lib/Optimized64/KeccakP-1600-timesN-AVX2.c(37): error C2143: syntax error: missing ';' before '='
  exit code: 2
```

It looks like the trouble comes from [these alignment directives](https://github.com/XKCP/K12/blob/27a84ecb811200990add07a047214f4ee7f77d48/lib/Optimized64/KeccakP-1600-timesN-AVX2.c#L36-L37), which were introduced in dbfe81a3b05db1f54081ffce491e2783b2a74230. I've hacked in some `#error` lines to confirm that MSCV is taking [the appropriate branch in `align.h`](https://github.com/XKCP/K12/blob/27a84ecb811200990add07a047214f4ee7f77d48/lib/align.h#L26-L27), but it's still very possible I'm doing something weird on my end. I've reproduced this failure above on GitHub CI and also separately on a Windows laptop running MSVC 14.29.30133. Any chance this is a legit build break?

### PR DESCRIPTION
**Pull request by mumbleskates**
This makes the order of align statements consistent with other usages, on declarations like KeccakP1600RoundConstants

Fixes #16

### CODE REVIEW

**Comment by oconnor663** [comment]
@mumbleskates Confirmed, works for me. CI is green on https://github.com/oconnor663/kangarootwelve_xkcp.rs/pull/5.
